# Generated by Django 4.2.5 on 2024-01-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariationimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='colorvariationimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sizevariation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sizevariation',
            name='remaing_stock',
        ),
        migrations.DeleteModel(
            name='ColorVariation',
        ),
        migrations.DeleteModel(
            name='ColorVariationImage',
        ),
    ]
