# Generated by Django 4.2.5 on 2024-01-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_colorvariationimage_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariation',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
